-- Adicionar Exercícios de Máquinas de Academia
-- Execute via Transaction Pooler

BEGIN;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES
-- CHEST MACHINES
(
    'ex046',
    'Voador na Máquina',
    'Peck Deck Machine',
    'chest',
    'inner-chest',
    '["peck deck machine"]'::jsonb,
    'beginner',
    '["pectoralis major"]'::jsonb,
    '["anterior deltoid"]'::jsonb,
    'isolation',
    'Isolamento de peitoral com segurança e foco na contração.',
    '["Ajuste o banco e os apoios","Sente-se com costas apoiadas","Traga os apoios à frente","Contraia o peitoral no centro","Retorne controladamente"]'::jsonb,
    '["Mantenha costas firmes no banco","Não use impulso","Foque na contração"]'::jsonb,
    'https://www.youtube.com/embed/Z6UT43S80Pk',
    '/exercises/peck-deck.gif',
    FALSE,
    NULL
),
(
    'ex047',
    'Supino na Máquina',
    'Chest Press Machine',
    'chest',
    'mid-chest',
    '["chest press machine"]'::jsonb,
    'beginner',
    '["pectoralis major"]'::jsonb,
    '["anterior deltoid","triceps"]'::jsonb,
    'compound',
    'Alternativa segura ao supino com barra.',
    '["Ajuste o banco na altura correta","Segure as alças","Empurre para frente até extensão","Retorne controladamente"]'::jsonb,
    '["Mantenha escápulas retraídas","Não trave os cotovelos completamente"]'::jsonb,
    'https://www.youtube.com/embed/xUm0BiZCWlQ',
    '/exercises/chest-press-machine.gif',
    FALSE,
    NULL
),

-- BACK MACHINES
(
    'ex048',
    'Remada Sentado na Máquina',
    'Seated Row Machine',
    'back',
    'mid-back',
    '["seated row machine"]'::jsonb,
    'beginner',
    '["latissimus dorsi","rhomboids"]'::jsonb,
    '["biceps","rear deltoid"]'::jsonb,
    'compound',
    'Excelente para espessura das costas com trajeto fixo.',
    '["Sente-se e apoie o peito no suporte","Segure as alças","Puxe em direção ao abdômen","Contraia as escápulas","Retorne controladamente"]'::jsonb,
    '["Mantenha peito apoiado","Puxe com os cotovelos","Não balance o tronco"]'::jsonb,
    'https://www.youtube.com/embed/sP_4vybjkE0',
    '/exercises/seated-row-machine.gif',
    FALSE,
    NULL
),
(
    'ex049',
    'Pulldown com Pegada Neutra',
    'Neutral Grip Pulldown',
    'back',
    'lats',
    '["cable","lat pulldown machine"]'::jsonb,
    'beginner',
    '["latissimus dorsi"]'::jsonb,
    '["biceps","rhomboids"]'::jsonb,
    'compound',
    'Variação confortável para os punhos.',
    '["Use barra paralela ou V","Sente-se e segure com pegada neutra","Puxe até o peito","Contraia as escápulas","Retorne controladamente"]'::jsonb,
    '["Incline levemente para trás","Foco em puxar com as costas"]'::jsonb,
    '',
    '/exercises/neutral-pulldown.gif',
    FALSE,
    NULL
),

-- SHOULDER MACHINES
(
    'ex050',
    'Desenvolvimento na Máquina',
    'Shoulder Press Machine',
    'shoulders',
    'anterior',
    '["shoulder press machine"]'::jsonb,
    'beginner',
    '["anterior deltoid"]'::jsonb,
    '["lateral deltoid","triceps"]'::jsonb,
    'compound',
    'Desenvolvimento com segurança e controle.',
    '["Ajuste o banco","Sente-se e segure as alças","Empurre para cima","Não trave completamente","Desça controladamente"]'::jsonb,
    '["Mantenha core contraído","Não arquee as costas"]'::jsonb,
    'https://www.youtube.com/embed/p9x3hwhg-kU',
    '/exercises/shoulder-press-machine.gif',
    FALSE,
    NULL
),
(
    'ex051',
    'Elevação Lateral no Cabo',
    'Cable Lateral Raise',
    'shoulders',
    'lateral',
    '["cable"]'::jsonb,
    'intermediate',
    '["lateral deltoid"]'::jsonb,
    '["anterior deltoid"]'::jsonb,
    'isolation',
    'Tensão constante durante todo o movimento.',
    '["Fique de lado à polia baixa","Segure a alça com a mão oposta","Eleve lateralmente até altura do ombro","Desça controladamente"]'::jsonb,
    '["Cotovelo levemente flexionado","Não use impulso","Movimento controlado"]'::jsonb,
    '',
    '/exercises/cable-lateral-raise.gif',
    FALSE,
    NULL
),
(
    'ex052',
    'Puxada Facial com Corda',
    'Face Pull',
    'shoulders',
    'posterior',
    '["cable"]'::jsonb,
    'intermediate',
    '["posterior deltoid"]'::jsonb,
    '["rhomboids","middle trapezius"]'::jsonb,
    'isolation',
    'Essencial para saúde dos ombros e postura.',
    '["Corda no pulley alto","Puxe em direção ao rosto","Separe a corda ao final","Cotovelos altos","Retorne controladamente"]'::jsonb,
    '["Foque nos ombros posteriores","Não use peso excessivo"]'::jsonb,
    'https://www.youtube.com/embed/rep-qVOkqgk',
    '/exercises/face-pull.gif',
    FALSE,
    NULL
),

-- LEG MACHINES
(
    'ex053',
    'Hack Squat',
    'Hack Squat Machine',
    'legs',
    'quadriceps',
    '["hack squat machine"]'::jsonb,
    'intermediate',
    '["quadriceps"]'::jsonb,
    '["glutes","hamstrings"]'::jsonb,
    'compound',
    'Agachamento com suporte nas costas.',
    '["Posicione-se na máquina","Pés na largura dos ombros","Libere a trava","Desça até 90 graus","Empurre de volta"]'::jsonb,
    '["Mantenha costas apoiadas","Joelhos alinhados com os pés","Não trave completamente"]'::jsonb,
    'https://www.youtube.com/embed/0tn5K9NlCfo',
    '/exercises/hack-squat.gif',
    FALSE,
    NULL
),
(
    'ex054',
    'Agachamento no Smith',
    'Smith Machine Squat',
    'legs',
    'quadriceps',
    '["smith machine"]'::jsonb,
    'beginner',
    '["quadriceps"]'::jsonb,
    '["glutes","hamstrings"]'::jsonb,
    'compound',
    'Agachamento com trajeto guiado.',
    '["Barra no trapézio","Pés ligeiramente à frente","Desça até paralela","Empurre de volta","Use travas de segurança"]'::jsonb,
    '["Mantenha core contraído","Peito erguido","Joelhos não passam dos pés"]'::jsonb,
    'https://www.youtube.com/embed/2SHsk9AzdjA',
    '/exercises/smith-squat.gif',
    FALSE,
    NULL
),
(
    'ex055',
    'Mesa Flexora Sentada',
    'Seated Leg Curl',
    'legs',
    'hamstrings',
    '["leg curl machine"]'::jsonb,
    'beginner',
    '["hamstrings"]'::jsonb,
    '["gastrocnemius"]'::jsonb,
    'isolation',
    'Variação sentada do leg curl.',
    '["Sente-se na máquina","Ajuste o rolo nas panturrilhas","Flexione as pernas para baixo","Contraia no final","Retorne controladamente"]'::jsonb,
    '["Segure firme nas alças","Movimento controlado","Não use impulso"]'::jsonb,
    '',
    '/exercises/seated-leg-curl.gif',
    FALSE,
    NULL
),
(
    'ex056',
    'Abdutora',
    'Hip Abductor Machine',
    'legs',
    'glutes',
    '["hip abductor machine"]'::jsonb,
    'beginner',
    '["gluteus medius","tensor fasciae latae"]'::jsonb,
    '[]'::jsonb,
    'isolation',
    'Isolamento do glúteo médio.',
    '["Sente-se na máquina","Ajuste os apoios externos","Abra as pernas contra a resistência","Contraia os glúteos","Retorne controladamente"]'::jsonb,
    '["Mantenha costas apoiadas","Movimento controlado","Não balance"]'::jsonb,
    '',
    '/exercises/hip-abductor.gif',
    FALSE,
    NULL
),
(
    'ex057',
    'Adutora',
    'Hip Adductor Machine',
    'legs',
    'adductors',
    '["hip adductor machine"]'::jsonb,
    'beginner',
    '["adductors"]'::jsonb,
    '[]'::jsonb,
    'isolation',
    'Fortalecimento dos adutores.',
    '["Sente-se na máquina","Ajuste os apoios internos","Feche as pernas contra a resistência","Contraia no final","Retorne controladamente"]'::jsonb,
    '["Movimento lento","Não use impulso","Mantenha postura"]'::jsonb,
    '',
    '/exercises/hip-adductor.gif',
    FALSE,
    NULL
),
(
    'ex058',
    'Panturrilha Sentado',
    'Seated Calf Raise',
    'legs',
    'calves',
    '["seated calf raise machine"]'::jsonb,
    'beginner',
    '["soleus"]'::jsonb,
    '["gastrocnemius"]'::jsonb,
    'isolation',
    'Foco no sóleo com joelhos flexionados.',
    '["Sente-se na máquina","Apoie os joelhos sob o suporte","Eleve as panturrilhas ao máximo","Contraia no topo","Desça alongando"]'::jsonb,
    '["Amplitude completa","Pause no topo","Controle a descida"]'::jsonb,
    '',
    '/exercises/seated-calf-raise.gif',
    FALSE,
    NULL
),

-- ARM MACHINES
(
    'ex059',
    'Rosca Direta no Cabo',
    'Cable Bicep Curl',
    'arms',
    'biceps',
    '["cable"]'::jsonb,
    'beginner',
    '["biceps brachii"]'::jsonb,
    '["brachialis","forearms"]'::jsonb,
    'isolation',
    'Tensão constante durante todo movimento.',
    '["Segure a barra no pulley baixo","Cotovelos fixos ao lado","Flexione os braços","Contraia os bíceps","Desça controladamente"]'::jsonb,
    '["Não balance o corpo","Mantenha cotovelos fixos","Controle total"]'::jsonb,
    '',
    '/exercises/cable-curl.gif',
    FALSE,
    NULL
),
(
    'ex060',
    'Tríceps na Máquina',
    'Tricep Extension Machine',
    'arms',
    'triceps',
    '["tricep extension machine"]'::jsonb,
    'beginner',
    '["triceps brachii"]'::jsonb,
    '[]'::jsonb,
    'isolation',
    'Isolamento de tríceps na máquina.',
    '["Ajuste o banco","Apoie os braços","Estenda os cotovelos","Contraia os tríceps","Retorne controladamente"]'::jsonb,
    '["Não despegue os braços do suporte","Movimento lento"]'::jsonb,
    '',
    '/exercises/tricep-machine.gif',
    FALSE,
    NULL
);

COMMIT;

-- Verificar inserção
SELECT COUNT(*) as total_exercicios FROM exercises;
SELECT category, COUNT(*) as count FROM exercises GROUP BY category ORDER BY count DESC;
