-- Seed exercises data
-- This file was auto-generated from src/data/exercises.js

BEGIN;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex001',
    'Supino Reto com Barra',
    'Barbell Bench Press',
    'chest',
    'mid-chest',
    '["barbell","bench"]'::jsonb,
    'intermediate',
    '["pectoralis major"]'::jsonb,
    '["anterior deltoid","triceps"]'::jsonb,
    'compound',
    'Exercício fundamental para desenvolvimento do peitoral.',
    '["Deite no banco com pés firmes no chão","Segure a barra com pegada pronada, mãos um pouco mais afastadas que a largura dos ombros","Desça a barra até tocar levemente o peito","Empurre a barra para cima até estender os braços"]'::jsonb,
    '["Mantenha escápulas retraídas","Não arquee excessivamente as costas"]'::jsonb,
    'https://www.youtube.com/embed/rT7DgCr-3BQ',
    '/exercises/bench-press.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex002',
    'Supino Inclinado com Halteres',
    'Incline Dumbbell Press',
    'chest',
    'upper-chest',
    '["dumbbells","bench"]'::jsonb,
    'intermediate',
    '["pectoralis major (clavicular)"]'::jsonb,
    '["anterior deltoid","triceps"]'::jsonb,
    'compound',
    'Foco na porção superior do peitoral.',
    '["Ajuste banco em 30-45 graus","Segure halteres na altura do peito","Empurre para cima convergindo no topo","Desça controladamente"]'::jsonb,
    '["Não eleve demais o banco","Mantenha cotovelos em 45 graus"]'::jsonb,
    'https://www.youtube.com/embed/0G2_XV7slIg',
    '/exercises/incline-db-press.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex003',
    'Crucifixo com Halteres',
    'Dumbbell Fly',
    'chest',
    'mid-chest',
    '["dumbbells","bench"]'::jsonb,
    'beginner',
    '["pectoralis major"]'::jsonb,
    '["anterior deltoid"]'::jsonb,
    'isolation',
    'Isolamento do peitoral com foco em alongamento.',
    '["Deite no banco segurando halteres acima do peito","Com leve flexão de cotovelo, abra os braços","Desça até sentir alongamento no peito","Volte controlado, contraindo o peitoral"]'::jsonb,
    '["Mantenha cotovelos levemente flexionados","Foco na contração"]'::jsonb,
    'https://www.youtube.com/embed/QENKPHhQVi4',
    '/exercises/db-fly.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex004',
    'Flexão de Braços',
    'Push-ups',
    'chest',
    'mid-chest',
    '["bodyweight"]'::jsonb,
    'beginner',
    '["pectoralis major"]'::jsonb,
    '["triceps","anterior deltoid","core"]'::jsonb,
    'compound',
    'Exercício clássico com peso corporal.',
    '["Posição de prancha com mãos na largura dos ombros","Desça o corpo até o peito quase tocar o chão","Empurre de volta à posição inicial","Mantenha core contraído"]'::jsonb,
    '["Corpo reto como uma tábua","Cotovelos em 45 graus"]'::jsonb,
    'https://www.youtube.com/embed/IODxDxX7oi4',
    '/exercises/pushup.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex005',
    'Crossover no Cabo',
    'Cable Crossover',
    'chest',
    'inner-chest',
    '["cable"]'::jsonb,
    'intermediate',
    '["pectoralis major"]'::jsonb,
    '["anterior deltoid"]'::jsonb,
    'isolation',
    'Excelente para definição e foco na parte interna.',
    '["Posicione-se entre as polias","Segure as alças com braços abertos","Traga as mãos à frente cruzando levemente","Retorne controladamente"]'::jsonb,
    '["Incline o tronco levemente à frente","Mantenha cotovelos levemente flexionados"]'::jsonb,
    NULL,
    '/exercises/cable-cross.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex006',
    'Puxada Frontal',
    'Lat Pulldown',
    'back',
    'lats',
    '["cable","lat pulldown machine"]'::jsonb,
    'beginner',
    '["latissimus dorsi"]'::jsonb,
    '["biceps","rhomboids","rear deltoid"]'::jsonb,
    'compound',
    'Principal exercício para largura das costas.',
    '["Sente-se e segure a barra com pegada pronada ampla","Puxe a barra até a altura do queixo","Contraia as escápulas","Retorne controladamente"]'::jsonb,
    '["Não balance o corpo","Foco em puxar com os cotovelos"]'::jsonb,
    'https://www.youtube.com/embed/SALxEARiMkw',
    '/exercises/lat-pulldown.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex007',
    'Remada Curvada com Barra',
    'Barbell Bent Over Row',
    'back',
    'mid-back',
    '["barbell"]'::jsonb,
    'intermediate',
    '["latissimus dorsi","rhomboids"]'::jsonb,
    '["biceps","erector spinae","rear deltoid"]'::jsonb,
    'compound',
    'Excelente para espessura das costas.',
    '["Incline o tronco a 45 graus","Segure a barra com braços estendidos","Puxe a barra em direção ao abdômen","Contraia as escápulas no topo"]'::jsonb,
    '["Mantenha costas retas","Não use impulso"]'::jsonb,
    'https://www.youtube.com/embed/FWJR5Ve8bnQ',
    '/exercises/bent-row.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex008',
    'Pulldown com Pegada Fechada',
    'Close Grip Pulldown',
    'back',
    'lats',
    '["cable"]'::jsonb,
    'beginner',
    '["latissimus dorsi"]'::jsonb,
    '["biceps","rhomboids"]'::jsonb,
    'compound',
    'Variação com maior amplitude de movimento.',
    '["Use triângulo ou barra V","Puxe em direção ao peito","Incline levemente o tronco para trás","Contraia e retorne"]'::jsonb,
    '["Foco na contração","Movimento controlado"]'::jsonb,
    NULL,
    '/exercises/close-pulldown.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex009',
    'Remada Unilateral com Halter',
    'One-Arm Dumbbell Row',
    'back',
    'lats',
    '["dumbbells","bench"]'::jsonb,
    'beginner',
    '["latissimus dorsi"]'::jsonb,
    '["biceps","rhomboids","rear deltoid"]'::jsonb,
    'compound',
    'Permite correção de desequilíbrios.',
    '["Apoie um joelho e mão no banco","Halter na mão oposta, braço estendido","Puxe o halter em direção ao quadril","Desça controladamente"]'::jsonb,
    '["Mantenha costas paralelas ao chão","Não gire o tronco"]'::jsonb,
    'https://www.youtube.com/embed/roCP6wCXPqo',
    '/exercises/db-row.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex010',
    'Barra Fixa',
    'Pull-ups',
    'back',
    'lats',
    '["pull-up bar"]'::jsonb,
    'advanced',
    '["latissimus dorsi"]'::jsonb,
    '["biceps","rhomboids","core"]'::jsonb,
    'compound',
    'Rei dos exercícios para costas.',
    '["Segure a barra com pegada pronada","Puxe o corpo até o queixo passar a barra","Desça controladamente até braços quase estendidos","Repita"]'::jsonb,
    '["Evite balançar","Inicie com negativas se necessário"]'::jsonb,
    'https://www.youtube.com/embed/eGo4IYlbE5g',
    '/exercises/pullup.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex011',
    'Desenvolvimento com Halteres',
    'Dumbbell Shoulder Press',
    'shoulders',
    'anterior',
    '["dumbbells"]'::jsonb,
    'intermediate',
    '["anterior deltoid"]'::jsonb,
    '["lateral deltoid","triceps","upper trapezius"]'::jsonb,
    'compound',
    'Principal exercício para ombros.',
    '["Sentado ou em pé, halteres na altura dos ombros","Empurre os halteres para cima","Estenda completamente os braços","Desça controladamente"]'::jsonb,
    '["Não arquee as costas","Core contraído"]'::jsonb,
    'https://www.youtube.com/embed/qEwKCR5JCog',
    '/exercises/db-press.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex012',
    'Elevação Lateral',
    'Lateral Raise',
    'shoulders',
    'lateral',
    '["dumbbells"]'::jsonb,
    'beginner',
    '["lateral deltoid"]'::jsonb,
    '["anterior deltoid","upper trapezius"]'::jsonb,
    'isolation',
    'Isolamento para largura dos ombros.',
    '["Em pé, halteres ao lado do corpo","Eleve os braços lateralmente até a altura dos ombros","Mantenha leve flexão de cotovelo","Desça controladamente"]'::jsonb,
    '["Não use impulso","Cotovelos sempre mais altos que os punhos"]'::jsonb,
    'https://www.youtube.com/embed/3VcKaXpzqRo',
    '/exercises/lateral-raise.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex013',
    'Elevação Frontal',
    'Front Raise',
    'shoulders',
    'anterior',
    '["dumbbells"]'::jsonb,
    'beginner',
    '["anterior deltoid"]'::jsonb,
    '["lateral deltoid"]'::jsonb,
    'isolation',
    'Foco na porção frontal do ombro.',
    '["Em pé, halteres à frente das coxas","Eleve os braços à frente até altura dos ombros","Desça controladamente"]'::jsonb,
    '["Alternado ou simultâneo","Evite balançar"]'::jsonb,
    NULL,
    '/exercises/front-raise.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex014',
    'Crucifixo Inverso',
    'Reverse Fly',
    'shoulders',
    'posterior',
    '["dumbbells"]'::jsonb,
    'beginner',
    '["posterior deltoid"]'::jsonb,
    '["rhomboids","middle trapezius"]'::jsonb,
    'isolation',
    'Essencial para ombros posteriores.',
    '["Incline o tronco à frente","Halteres abaixo com braços quase estendidos","Eleve os braços lateralmente","Contraia escápulas no topo"]'::jsonb,
    '["Mantenha cotovelos levemente flexionados","Controle o movimento"]'::jsonb,
    'https://www.youtube.com/embed/lPt0GqwaqEw',
    '/exercises/reverse-fly.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex015',
    'Desenvolvimento Arnold',
    'Arnold Press',
    'shoulders',
    'all',
    '["dumbbells"]'::jsonb,
    'intermediate',
    '["anterior deltoid","lateral deltoid"]'::jsonb,
    '["triceps"]'::jsonb,
    'compound',
    'Variação que trabalha todas as porções.',
    '["Halteres na frente do rosto, palmas para você","Gire os pulsos enquanto empurra","Termine com palmas para frente","Desça revertendo o movimento"]'::jsonb,
    '["Movimento fluido","Controle total"]'::jsonb,
    'https://www.youtube.com/embed/3ml7BH7mNwQ',
    '/exercises/arnold-press.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex016',
    'Rosca Direta com Barra',
    'Barbell Curl',
    'arms',
    'biceps',
    '["barbell"]'::jsonb,
    'beginner',
    '["biceps brachii"]'::jsonb,
    '["brachialis","forearms"]'::jsonb,
    'isolation',
    'Clássico para bíceps.',
    '["Em pé, barra com pegada supinada","Flexione os cotovelos","Suba a barra até o peito","Desça controladamente"]'::jsonb,
    '["Cotovelos fixos ao lado do corpo","Não balance"]'::jsonb,
    'https://www.youtube.com/embed/kwG2ipFRgfo',
    '/exercises/barbell-curl.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex017',
    'Rosca Alternada com Halteres',
    'Alternating Dumbbell Curl',
    'arms',
    'biceps',
    '["dumbbells"]'::jsonb,
    'beginner',
    '["biceps brachii"]'::jsonb,
    '["brachialis"]'::jsonb,
    'isolation',
    'Permite foco em cada braço.',
    '["Em pé, halteres ao lado do corpo","Alterne flexionando um braço de cada vez","Supine o punho durante a subida","Desça controladamente"]'::jsonb,
    '["Mantenha postura ereta","Concentre no bíceps"]'::jsonb,
    'https://www.youtube.com/embed/sAq_ocpRh_I',
    '/exercises/alt-curl.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex018',
    'Rosca Martelo',
    'Hammer Curl',
    'arms',
    'biceps',
    '["dumbbells"]'::jsonb,
    'beginner',
    '["brachialis","biceps brachii"]'::jsonb,
    '["brachioradialis"]'::jsonb,
    'isolation',
    'Foco no braquial e antebraço.',
    '["Halteres com pegada neutra (martelo)","Flexione os cotovelos mantendo pegada","Suba até contração máxima","Desça controladamente"]'::jsonb,
    '["Punhos alinhados","Cotovelos fixos"]'::jsonb,
    'https://www.youtube.com/embed/zC3nLlEvin4',
    '/exercises/hammer-curl.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex019',
    'Rosca Concentrada',
    'Concentration Curl',
    'arms',
    'biceps',
    '["dumbbells"]'::jsonb,
    'intermediate',
    '["biceps brachii"]'::jsonb,
    '["brachialis"]'::jsonb,
    'isolation',
    'Máximo isolamento do bíceps.',
    '["Sentado, cotovelo apoiado na parte interna da coxa","Halter pendente","Flexione concentrando no bíceps","Contraia no topo e desça"]'::jsonb,
    '["Movimento lento e controlado","Foco na contração"]'::jsonb,
    'https://www.youtube.com/embed/0AUGkch3tzc',
    '/exercises/concentration-curl.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex020',
    'Tríceps Pulley',
    'Tricep Pushdown',
    'arms',
    'triceps',
    '["cable"]'::jsonb,
    'beginner',
    '["triceps brachii"]'::jsonb,
    '[]'::jsonb,
    'isolation',
    'Isolamento de tríceps no cabo.',
    '["Segure a barra ou corda no pulley alto","Cotovelos fixos ao lado do corpo","Estenda os braços completamente","Retorne controladamente"]'::jsonb,
    '["Não mova os cotovelos","Contraia no final"]'::jsonb,
    'https://www.youtube.com/embed/2-LAMcpzODU',
    '/exercises/pushdown.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex021',
    'Tríceps Testa',
    'Skull Crushers',
    'arms',
    'triceps',
    '["barbell","bench"]'::jsonb,
    'intermediate',
    '["triceps brachii"]'::jsonb,
    '[]'::jsonb,
    'isolation',
    'Excelente para cabeça longa do tríceps.',
    '["Deite no banco, barra acima do peito","Flexione apenas os cotovelos","Desça a barra em direção à testa","Estenda de volta"]'::jsonb,
    '["Cotovelos apontados para cima","Controle total"]'::jsonb,
    'https://www.youtube.com/embed/d_KZxkY_0cM',
    '/exercises/skull-crusher.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex022',
    'Mergulho no Banco',
    'Bench Dips',
    'arms',
    'triceps',
    '["bench"]'::jsonb,
    'beginner',
    '["triceps brachii"]'::jsonb,
    '["anterior deltoid","pectoralis major"]'::jsonb,
    'compound',
    'Exercício com peso corporal.',
    '["Mãos no banco atrás de você","Pernas estendidas ou flexionadas","Desça flexionando os cotovelos","Empurre de volta"]'::jsonb,
    '["Não desça demais","Cotovelos para trás"]'::jsonb,
    NULL,
    '/exercises/bench-dips.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex023',
    'Tríceps Francês',
    'Overhead Tricep Extension',
    'arms',
    'triceps',
    '["dumbbells"]'::jsonb,
    'intermediate',
    '["triceps brachii"]'::jsonb,
    '[]'::jsonb,
    'isolation',
    'Alonga e trabalha o tríceps.',
    '["Halter acima da cabeça com as duas mãos","Flexione os cotovelos descendo atrás da cabeça","Estenda de volta","Mantenha cotovelos apontados para cima"]'::jsonb,
    '["Não deixe cotovelos abrirem","Controle o peso"]'::jsonb,
    'https://www.youtube.com/embed/_gsUck-7M74',
    '/exercises/overhead-ext.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex024',
    'Agachamento Livre',
    'Barbell Back Squat',
    'legs',
    'quadriceps',
    '["barbell","squat rack"]'::jsonb,
    'intermediate',
    '["quadriceps"]'::jsonb,
    '["glutes","hamstrings","core","erector spinae"]'::jsonb,
    'compound',
    'Rei dos exercícios para pernas.',
    '["Barra apoiada no trapézio","Pés na largura dos ombros","Desça até coxas paralelas ao chão","Empurre de volta"]'::jsonb,
    '["Joelhos na direção dos pés","Peito erguido"]'::jsonb,
    'https://www.youtube.com/embed/ultWZbUMPL8',
    '/exercises/squat.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex025',
    'Leg Press 45°',
    'Leg Press',
    'legs',
    'quadriceps',
    '["leg press machine"]'::jsonb,
    'beginner',
    '["quadriceps"]'::jsonb,
    '["glutes","hamstrings"]'::jsonb,
    'compound',
    'Grande volume com segurança.',
    '["Sente-se na máquina","Pés na plataforma, largura do quadril","Desça controladamente","Empurre sem travar joelhos"]'::jsonb,
    '["Não tire o quadril do apoio","Joelhos não colapsam"]'::jsonb,
    'https://www.youtube.com/embed/GvRgijoJ2xY',
    '/exercises/leg-press.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex026',
    'Cadeira Extensora',
    'Leg Extension',
    'legs',
    'quadriceps',
    '["leg extension machine"]'::jsonb,
    'beginner',
    '["quadriceps"]'::jsonb,
    '[]'::jsonb,
    'isolation',
    'Isolamento de quadríceps.',
    '["Sente-se na máquina, tornozelos sob o rolo","Estenda as pernas","Contraia no topo","Desça controladamente"]'::jsonb,
    '["Não use impulso","Segure na contração"]'::jsonb,
    NULL,
    '/exercises/leg-ext.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex027',
    'Avanço com Halteres',
    'Dumbbell Lunges',
    'legs',
    'quadriceps',
    '["dumbbells"]'::jsonb,
    'intermediate',
    '["quadriceps","glutes"]'::jsonb,
    '["hamstrings","core"]'::jsonb,
    'compound',
    'Unilateral para equilíbrio.',
    '["Halteres nas mãos","Dê um passo à frente","Desça até joelho traseiro quase tocar o chão","Empurre de volta"]'::jsonb,
    '["Joelho frontal não passa do pé","Tronco ereto"]'::jsonb,
    'https://www.youtube.com/embed/D7KaRcUTQeE',
    '/exercises/lunges.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex028',
    'Agachamento Búlgaro',
    'Bulgarian Split Squat',
    'legs',
    'quadriceps',
    '["dumbbells","bench"]'::jsonb,
    'advanced',
    '["quadriceps","glutes"]'::jsonb,
    '["hamstrings"]'::jsonb,
    'compound',
    'Avançado para unilateral.',
    '["Pé traseiro elevado no banco","Halteres nas mãos","Desça até joelho quase tocar o chão","Empurre com a perna da frente"]'::jsonb,
    '["Mantenha equilíbrio","Core contraído"]'::jsonb,
    'https://www.youtube.com/embed/2C-uNgKwPLE',
    '/exercises/bulgarian.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex029',
    'Stiff',
    'Romanian Deadlift',
    'legs',
    'hamstrings',
    '["barbell"]'::jsonb,
    'intermediate',
    '["hamstrings","glutes"]'::jsonb,
    '["erector spinae"]'::jsonb,
    'compound',
    'Foco em posteriores de coxa.',
    '["Barra na frente das coxas","Incline o tronco mantendo costas retas","Desça até alongar posterior","Volte contraindo glúteos"]'::jsonb,
    '["Joelhos levemente flexionados","Barra próxima ao corpo"]'::jsonb,
    'https://www.youtube.com/embed/JCXUYuzwNrM',
    '/exercises/rdl.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex030',
    'Mesa Flexora',
    'Lying Leg Curl',
    'legs',
    'hamstrings',
    '["leg curl machine"]'::jsonb,
    'beginner',
    '["hamstrings"]'::jsonb,
    '["calves"]'::jsonb,
    'isolation',
    'Isolamento de posterior.',
    '["Deite na máquina","Tornozelos sob o rolo","Flexione as pernas","Contraia e retorne"]'::jsonb,
    '["Não levante o quadril","Controle a descida"]'::jsonb,
    NULL,
    '/exercises/leg-curl.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex031',
    'Hip Thrust',
    'Barbell Hip Thrust',
    'legs',
    'glutes',
    '["barbell","bench"]'::jsonb,
    'intermediate',
    '["glutes"]'::jsonb,
    '["hamstrings","core"]'::jsonb,
    'compound',
    'Melhor exercício para glúteos.',
    '["Costas apoiadas no banco","Barra sobre o quadril","Empurre o quadril para cima","Contraia glúteos no topo"]'::jsonb,
    '["Queixo no peito","Não hiperestenda"]'::jsonb,
    'https://www.youtube.com/embed/SEdqd1n0cvg',
    '/exercises/hip-thrust.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex032',
    'Elevação Pélvica',
    'Glute Bridge',
    'legs',
    'glutes',
    '["bodyweight"]'::jsonb,
    'beginner',
    '["glutes"]'::jsonb,
    '["hamstrings","core"]'::jsonb,
    'isolation',
    'Ativação de glúteos.',
    '["Deite com joelhos flexionados","Pés no chão","Eleve o quadril contraindo glúteos","Desça controladamente"]'::jsonb,
    '["Não arquee lombar","Segure no topo"]'::jsonb,
    NULL,
    '/exercises/glute-bridge.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex033',
    'Panturrilha em Pé',
    'Standing Calf Raise',
    'legs',
    'calves',
    '["calf raise machine"]'::jsonb,
    'beginner',
    '["gastrocnemius"]'::jsonb,
    '["soleus"]'::jsonb,
    'isolation',
    'Desenvolvimento de panturrilhas.',
    '["Ombros sob os apoios","Fique na ponta dos pés","Eleve ao máximo","Desça alongando"]'::jsonb,
    '["Movimento completo","Pause no topo"]'::jsonb,
    NULL,
    '/exercises/calf-raise.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex034',
    'Panturrilha Sentado',
    'Seated Calf Raise',
    'legs',
    'calves',
    '["seated calf machine"]'::jsonb,
    'beginner',
    '["soleus"]'::jsonb,
    '["gastrocnemius"]'::jsonb,
    'isolation',
    'Foco no sóleo.',
    '["Sente com joelhos sob o apoio","Eleve os calcanhares","Contraia no topo","Desça alongando"]'::jsonb,
    '["Joelhos em 90 graus","Controle total"]'::jsonb,
    NULL,
    '/exercises/seated-calf.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex035',
    'Prancha',
    'Plank',
    'core',
    'abs',
    '["bodyweight"]'::jsonb,
    'beginner',
    '["rectus abdominis","transverse abdominis"]'::jsonb,
    '["obliques","erector spinae"]'::jsonb,
    'isometric',
    'Estabilização do core.',
    '["Apoie antebraços e pontas dos pés","Corpo reto como uma tábua","Mantenha a posição","Respire normalmente"]'::jsonb,
    '["Não deixe quadril subir ou descer","Glúteos contraídos"]'::jsonb,
    'https://www.youtube.com/embed/pSHjTRCQxIw',
    '/exercises/plank.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex036',
    'Abdominal Crunch',
    'Crunch',
    'core',
    'abs',
    '["bodyweight"]'::jsonb,
    'beginner',
    '["rectus abdominis"]'::jsonb,
    '[]'::jsonb,
    'isolation',
    'Clássico para abdômen.',
    '["Deite com joelhos flexionados","Mãos atrás da cabeça","Eleve ombros do chão","Contraia e desça"]'::jsonb,
    '["Não puxe a cabeça","Foco na contração"]'::jsonb,
    NULL,
    '/exercises/crunch.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex037',
    'Prancha Lateral',
    'Side Plank',
    'core',
    'obliques',
    '["bodyweight"]'::jsonb,
    'intermediate',
    '["obliques"]'::jsonb,
    '["transverse abdominis"]'::jsonb,
    'isometric',
    'Fortalece oblíquos.',
    '["Apoie um antebraço e lateral do pé","Corpo em linha reta","Mantenha a posição","Troque o lado"]'::jsonb,
    '["Quadril elevado","Não deixe cair"]'::jsonb,
    NULL,
    '/exercises/side-plank.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex038',
    'Elevação de Pernas',
    'Hanging Leg Raise',
    'core',
    'lower-abs',
    '["pull-up bar"]'::jsonb,
    'advanced',
    '["rectus abdominis","hip flexors"]'::jsonb,
    '["obliques"]'::jsonb,
    'isolation',
    'Avançado para abdômen inferior.',
    '["Pendure na barra","Eleve as pernas retas até 90 graus","Desça controladamente","Não balance"]'::jsonb,
    '["Movimento controlado","Pode flexionar joelhos para facilitar"]'::jsonb,
    NULL,
    '/exercises/leg-raise.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex039',
    'Russian Twist',
    'Russian Twist',
    'core',
    'obliques',
    '["bodyweight","medicine ball"]'::jsonb,
    'intermediate',
    '["obliques"]'::jsonb,
    '["rectus abdominis"]'::jsonb,
    'rotation',
    'Rotacional para oblíquos.',
    '["Sente inclinado para trás","Pés elevados ou no chão","Gire o tronco de um lado ao outro","Peso opcional nas mãos"]'::jsonb,
    '["Movimento vem do core","Não apenas mova os braços"]'::jsonb,
    NULL,
    '/exercises/russian-twist.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex040',
    'Dead Bug',
    'Dead Bug',
    'core',
    'stability',
    '["bodyweight"]'::jsonb,
    'beginner',
    '["transverse abdominis","rectus abdominis"]'::jsonb,
    '["hip flexors"]'::jsonb,
    'stability',
    'Estabilidade anti-extensão.',
    '["Deite com braços estendidos para cima","Joelhos em 90 graus","Estenda braço e perna opostos","Alterne mantendo lombar no chão"]'::jsonb,
    '["Lombar sempre pressionada no chão","Movimento lento"]'::jsonb,
    NULL,
    '/exercises/dead-bug.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex041',
    'Burpee',
    'Burpee',
    'cardio',
    'hiit',
    '["bodyweight"]'::jsonb,
    'intermediate',
    '["full body"]'::jsonb,
    '[]'::jsonb,
    'cardio',
    'Exercício completo de alta intensidade.',
    '["Em pé, agache e coloque mãos no chão","Salte os pés para trás em posição de flexão","Faça uma flexão (opcional)","Pule os pés de volta e salte"]'::jsonb,
    '["Mantenha ritmo constante","Modifique conforme necessário"]'::jsonb,
    NULL,
    '/exercises/burpee.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex042',
    'Mountain Climber',
    'Mountain Climber',
    'cardio',
    'hiit',
    '["bodyweight"]'::jsonb,
    'beginner',
    '["core","hip flexors"]'::jsonb,
    '["shoulders"]'::jsonb,
    'cardio',
    'Cardio e core simultâneos.',
    '["Posição de flexão","Traga um joelho ao peito","Alterne rapidamente","Mantenha core contraído"]'::jsonb,
    '["Quadril baixo","Movimento rápido"]'::jsonb,
    NULL,
    '/exercises/mountain-climber.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex043',
    'Jumping Jacks',
    'Jumping Jacks',
    'cardio',
    'warmup',
    '["bodyweight"]'::jsonb,
    'beginner',
    '["full body"]'::jsonb,
    '[]'::jsonb,
    'cardio',
    'Aquecimento clássico.',
    '["Em pé, pés juntos","Salte abrindo pernas e braços","Retorne à posição inicial","Repita rapidamente"]'::jsonb,
    '["Movimento fluido","Bom para aquecimento"]'::jsonb,
    NULL,
    '/exercises/jumping-jacks.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex044',
    'High Knees',
    'High Knees',
    'cardio',
    'hiit',
    '["bodyweight"]'::jsonb,
    'beginner',
    '["hip flexors","quadriceps"]'::jsonb,
    '["core"]'::jsonb,
    'cardio',
    'Elevação de joelhos para cardio.',
    '["Corra no lugar","Eleve joelhos à altura do quadril","Movimente braços","Mantenha ritmo acelerado"]'::jsonb,
    '["Foque na altura dos joelhos","Core engajado"]'::jsonb,
    NULL,
    '/exercises/high-knees.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;

INSERT INTO exercises (
    id, name, name_en, category, subcategory, equipment,
    difficulty, primary_muscles, secondary_muscles, type,
    description, steps, tips, demo_video, demo_image, is_custom, user_id
) VALUES (
    'ex045',
    'Squat Jump',
    'Jump Squat',
    'cardio',
    'plyometrics',
    '["bodyweight"]'::jsonb,
    'intermediate',
    '["quadriceps","glutes"]'::jsonb,
    '["calves"]'::jsonb,
    'plyometric',
    'Explosão para pernas.',
    '["Faça um agachamento","Exploda para cima em um salto","Aterrisse suavemente","Repita imediatamente"]'::jsonb,
    '["Aterrisse com joelhos flexionados","Absorva o impacto"]'::jsonb,
    NULL,
    '/exercises/squat-jump.gif',
    FALSE,
    NULL
) ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    name_en = EXCLUDED.name_en,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    primary_muscles = EXCLUDED.primary_muscles,
    secondary_muscles = EXCLUDED.secondary_muscles,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    steps = EXCLUDED.steps,
    tips = EXCLUDED.tips,
    demo_video = EXCLUDED.demo_video,
    demo_image = EXCLUDED.demo_image;


COMMIT;

-- Verify insertion
SELECT category, COUNT(*) as count
FROM exercises
WHERE user_id IS NULL
GROUP BY category
ORDER BY category;
